{
 "title": "Tailscale / Overview",
 "description": "An overview of Tailscale API metrics including tailnet settings, devices (OS, version, authorization, routes), users (role, status, login state), auth keys, and Services. The dashboards were generated using [tailscale-mixin](https://github.com/adinhodovic/tailscale-exporter/tree/main/tailscale-mixin). Open issues and create feature requests in the repository.",
 "tags": [
  "tailscale",
  "headscale",
  "tailscaled",
  "tailscale-mixin"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(tailscale_up{}, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(tailscale_up{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(tailscale_up{cluster=\"$cluster\", namespace=\"$namespace\"}, job)"
   },
   {
    "name": "tailnet",
    "label": "Tailnet",
    "query": "label_values(tailscale_up{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\"}, tailnet)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users",
   "type": "stat",
   "description": "The total number of users in the selected tailnet.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  tailscale_users_info{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "stat",
   "description": "The total number of devices in the selected tailnet.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  tailscale_devices_info{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Devices Logged In",
   "type": "stat",
   "description": "The total number of devices that are currently online in the selected tailnet.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  tailscale_devices_online{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "stat",
   "description": "The total number of keys in the selected tailnet.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  tailscale_keys_info{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Nameservers",
   "type": "table",
   "description": "A table showing the nameservers configured for the selected tailnet.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum(\n  tailscale_dns_nameservers_info{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (nameserver)\n"
    }
   ]
  },
  {
   "title": "Magic DNS Enabled",
   "type": "stat",
   "description": "Whether Magic DNS is enabled for the selected tailnet.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "sum(\n  tailscale_dns_magic_dns{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Tailnet Settings",
   "type": "table",
   "description": "A table showing the current settings for the selected tailnet.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "tailscale_tailnet_settings_info{\n  cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n}\n"
    }
   ]
  },
  { "title": "Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Devices by OS",
   "type": "piechart",
   "description": "A pie chart showing the distribution of devices by operating system in the selected tailnet.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  tailscale_devices_info{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (os)\n",
     "legendFormat": "{{ os }}"
    }
   ]
  },
  {
   "title": "Devices by Version",
   "type": "piechart",
   "description": "A pie chart showing the distribution of devices by Tailscale client version in the selected tailnet.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  tailscale_devices_info{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (client_version)\n",
     "legendFormat": "{{ client_version }}"
    }
   ]
  },
  {
   "title": "Devices with Update Available",
   "type": "piechart",
   "description": "The total number of devices that have an update available in the selected tailnet.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  tailscale_devices_update_available{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  } == 1\n)\n",
     "legendFormat": "Update Available"
    },
    {
     "expr": "count(\n  tailscale_devices_update_available{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  } == 0\n)\n",
     "legendFormat": "No Update Available"
    }
   ]
  },
  {
   "title": "Authorized Devices",
   "type": "piechart",
   "description": "The total number of devices that are authorized to access the tailnet.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  tailscale_devices_authorized{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  } == 1\n)\n",
     "legendFormat": "Authorized"
    },
    {
     "expr": "count(\n  tailscale_devices_authorized{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  } == 0\n)\n",
     "legendFormat": "Not Authorized"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "description": "A table showing all devices in the selected tailnet.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "tailscale_devices_info{\n  cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n}\n"
    }
   ]
  },
  {
   "title": "Devices Settings",
   "type": "table",
   "description": "A table showing all devices in the selected tailnet.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "min(\n  tailscale_devices_created_timestamp{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  } * 1000\n) by (name, id)\n"
    },
    {
     "expr": "min(\n  tailscale_devices_expires_timestamp{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  } * 1000\n) by (name, id)\n"
    },
    {
     "expr": "sum(\n  tailscale_devices_authorized{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (name, id)\n"
    },
    {
     "expr": "sum(\n  tailscale_devices_blocks_incoming{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (name, id)\n"
    },
    {
     "expr": "sum(\n  tailscale_devices_routes_enabled{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (name, id)\n"
    },
    {
     "expr": "sum(\n  tailscale_devices_routes_advertised{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (name, id)\n"
    },
    {
     "expr": "sum(\n  tailscale_devices_key_expiry_disabled{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (name, id)\n"
    },
    {
     "expr": "sum(\n  tailscale_devices_external{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (name, id)\n"
    }
   ]
  },
  {
   "title": "Devices Requiring Attention",
   "type": "table",
   "description": "Devices with operational follow-up items: available client updates, missing authorization, or advertised routes that are not enabled.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  tailscale_devices_update_available{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (name, id)\n== 1\n"
    },
    {
     "expr": "1\n-\nsum(\n  tailscale_devices_authorized{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (name, id)\n> 0\n"
    },
    {
     "expr": "sum(\n  tailscale_devices_routes_advertised{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (name, id)\n-\nsum(\n  tailscale_devices_routes_enabled{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (name, id)\n> 0\n"
    }
   ]
  },
  {
   "title": "Update Available",
   "type": "timeseries",
   "description": "A timeseries panel showing devices that have an update available.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "sum(\n  tailscale_devices_update_available{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (name, id)\n== 1\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Time Since Last Seen",
   "type": "timeseries",
   "description": "A timeseries panel showing the last time a device was seen.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() -\nmax(\n  tailscale_devices_last_seen_timestamp{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (name, id, client_version)\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Users by Role",
   "type": "piechart",
   "description": "A pie chart showing the distribution of users by role in the selected tailnet.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  tailscale_users_info{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (role)\n",
     "legendFormat": "{{ role }}"
    }
   ]
  },
  {
   "title": "Users by Status",
   "type": "piechart",
   "description": "A pie chart showing the distribution of users by status in the selected tailnet.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  tailscale_users_info{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (status)\n",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Users by Type",
   "type": "piechart",
   "description": "A pie chart showing the distribution of users by type in the selected tailnet.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  tailscale_users_info{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (type)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Users Logged In",
   "type": "piechart",
   "description": "The total number of users that are currently logged in to the selected tailnet.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  tailscale_users_currently_logged_in{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  } == 1\n)\n",
     "legendFormat": "Logged In"
    },
    {
     "expr": "count(\n  tailscale_users_currently_logged_in{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  } == 0\n)\n",
     "legendFormat": "Logged Out"
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "description": "A table showing all users in the selected tailnet.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tailscale_users_info{\n  cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n}\n"
    },
    {
     "expr": "min(\n  tailscale_users_created_timestamp{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  } * 1000\n) by (name, id)\n"
    },
    {
     "expr": "max(\n  tailscale_users_last_seen_timestamp{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  } * 1000\n) by (name, id)\n"
    }
   ]
  },
  { "title": "Keys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Keys",
   "type": "table",
   "description": "A table showing all keys in the selected tailnet.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "tailscale_keys_info{\n  cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n}\n"
    },
    {
     "expr": "min(\n  tailscale_keys_created_timestamp{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  } * 1000\n) by (name, id, key_type, user_id)\n"
    },
    {
     "expr": "min(\n  tailscale_keys_expires_timestamp{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  } * 1000\n) by (name, id, key_type, user_id)\n"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Services",
   "type": "table",
   "description": "A table showing Tailscale Services and their advertised address and port counts.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name, comment, tags) (\n  tailscale_services_info{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n)\n"
    },
    {
     "expr": "sum by (name) (\n  tailscale_services_address{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n)\n"
    },
    {
     "expr": "sum by (name) (\n  tailscale_services_port{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n)\n"
    }
   ]
  }
 ]
}