version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    assignees:
      - adinhodovic
    schedule:
      interval: monthly
    cooldown:
      default-days: 14
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /tailscale-mixin/scripts
    assignees:
      - adinhodovic
    schedule:
      interval: monthly
    cooldown:
      default-days: 14
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    assignees:
      - adinhodovic
    schedule:
      interval: monthly
    cooldown:
      default-days: 14
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
    groups:
      github-actions:
        patterns:
          - "*"
