---
version: "2"

formatters:
  enable:
    - goimports # checks if the code and import statements are formatted according to the 'goimports' command
    - golines # checks if code is formatted, and fixes long lines
    - gofumpt # enforces a stricter format than 'gofmt', while being backwards compatible
    - swaggo # formats swaggo comments

  settings:
    golines:
      max-len: 100
