name: CI

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!tailscale-mixin/**"
  pull_request:
    branches:
      - main
    paths:
      - "**"
      - "!tailscale-mixin/**"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        id: go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.25

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          # Build golangci-lint from source with the configured Go version
          install-mode: goinstall
          version: latest

      # - name: Build
      #   run: make build
      #
      - name: Run unit tests
        run: go install github.com/go-delve/delve/cmd/dlv@latest && go test ./... -v -covermode=count -coverprofile=coverage.txt
