name: CI

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!tailscale-mixin/**"
      - "!deploy/**"
  pull_request:
    branches:
      - main
    paths:
      - "**"
      - "!tailscale-mixin/**"
      - "!deploy/**"
  release:
    types:
      - published

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        id: go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.25

      - name: Golang CI Lint
        uses: golangci/golangci-lint-action@v8
        with:
          install-mode: goinstall
          version: latest

      - name: Build
        run: make build

      - name: Run unit tests
        run: go install github.com/go-delve/delve/cmd/dlv@latest && go test ./... -v -covermode=count -coverprofile=coverage.txt

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Test
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: adinhodovic/tailscale-exporter:latest

  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event_name == 'release'
    needs:
      - test
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: adinhodovic/tailscale-exporter:latest,adinhodovic/tailscale-exporter:${{ github.event.release.tag_name }}

      - name: Build Binary
        run: |
          make build-linux-amd64

      - name: Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            tailscale-exporter-linux-amd64
