name: ci
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - "tailscale-mixin/**"
      - ".github/workflows/mixin.yml"
  pull_request:
    paths:
      - "tailscale-mixin/**"
      - ".github/workflows/mixin.yml"

defaults:
  run:
    working-directory: ./tailscale-mixin
jobs:
  matrix:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Lint Alerts
            run: make --always-make alerts-lint
          - name: Generate yaml
            run: make --always-make generate && git diff --exit-code
          - name: Lint Grafana Dashboards
            run: make --always-make dashboards-lint
          - name: Format Jsonnet
            run: make --always-make jsonnet-fmt && git diff --exit-code
          - name: Lint Jsonnet
            run: make --always-make jsonnet-lint
          - name: Format Markdown
            run: make --always-make markdownfmt && git diff --exit-code
          - name: Lint Markdown
            run: make --always-make vale && git diff --exit-code
          - name: Lint YAML
            run: make --always-make pint-lint
          - name: Run unit tests
            run: make --always-make test

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: ./tailscale-mixin/scripts/go.mod
          cache-dependency-path: ./tailscale-mixin/scripts/go.sum
      - run: ${{ matrix.run }}
